allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
provisioner: {{ $.Values.storageClass.provisioner }}
{{- if $.Values.storageClass.parameters }}
parameters: {{ $.Values.storageClass.parameters }}
{{- end }}