apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gridgain-app
  namespace: gridgain
spec:
  hosts:
    - "*"
  gateways:
    - default/backend-gateway
  http:
    - name: gridgain
      match:
        - uri:
            prefix: /gridgain
      rewrite:
        uri: /ignite/$2
      route:
        - destination:
            host: gridgain-service
            port:
              number: 8080