apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cluster-vs
  namespace: gridgain
spec:
  hosts:
  - "{{ .Values.gateway.hosts }}" # use DNS name if deploying on AKS, GKE or EKS. Use * if deploying on local machine using Docker desktop
  gateways:
  - default/backend-gateway
  http:
  - name: ignite-cluster
    match:
    - uri:
        prefix: /ignite/
    rewrite:
      uri: /ignite/$2
    route:
    - destination:
        host: gridgain-service
        port:
          number: 8080