apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: default
  name: backend-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.gateway.hosts }}" # use DNS name if deploying on AKS, GKE or EKS. Use * if deploying on local machine using Docker desktop
#      tls:
#        httpsRedirect: true