apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: all-traffic
  namespace: istio-system
spec:
  hosts:
    - "localhost"
  ports:
    - number: 80
      name: http-port
      protocol: HTTP